/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.costales_program;
import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class menu_dsa extends javax.swing.JFrame {

    /**
     * Creates new form menu_dsa
     */
    public menu_dsa() {
        initComponents();
    }
int total;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSnack3 = new javax.swing.JCheckBox();
        cbSnack1 = new javax.swing.JCheckBox();
        cbSnack2 = new javax.swing.JCheckBox();
        cbDrink3 = new javax.swing.JCheckBox();
        cbDrink1 = new javax.swing.JCheckBox();
        cbDrink2 = new javax.swing.JCheckBox();
        btnTotal = new javax.swing.JButton();
        cbEnableS = new javax.swing.JCheckBox();
        cbEnableD = new javax.swing.JCheckBox();
        txtPayment = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTotal1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbSnack3.setText("Fries - 45");
        cbSnack3.setEnabled(false);
        getContentPane().add(cbSnack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cbSnack1.setText("Hotdog - 35");
        cbSnack1.setEnabled(false);
        getContentPane().add(cbSnack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        cbSnack2.setText("Burger - 50");
        cbSnack2.setEnabled(false);
        getContentPane().add(cbSnack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        cbDrink3.setText("Buko Juice -15");
        cbDrink3.setEnabled(false);
        getContentPane().add(cbDrink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        cbDrink1.setText("Coke - 25");
        cbDrink1.setEnabled(false);
        getContentPane().add(cbDrink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        cbDrink2.setText("Juice - 20");
        cbDrink2.setEnabled(false);
        getContentPane().add(cbDrink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        btnTotal.setBackground(new java.awt.Color(0, 255, 0));
        btnTotal.setText("Pay");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        cbEnableS.setText("Snacks");
        cbEnableS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnableSActionPerformed(evt);
            }
        });
        getContentPane().add(cbEnableS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cbEnableD.setText("Drink");
        cbEnableD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnableDActionPerformed(evt);
            }
        });
        getContentPane().add(cbEnableD, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 150, -1));

        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        lblChange.setText("Change:");
        getContentPane().add(lblChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adriane's Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adriane's Menu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        btnTotal1.setBackground(new java.awt.Color(0, 255, 0));
        btnTotal1.setText("Pay");
        btnTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotal1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentActionPerformed

    private void cbEnableSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnableSActionPerformed
        // TODO add your handling code here:
        cbSnack1.setEnabled(true);
        cbSnack2.setEnabled(true);
        cbSnack3.setEnabled(true);
       
    }//GEN-LAST:event_cbEnableSActionPerformed

    private void cbEnableDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnableDActionPerformed
        // TODO add your handling code here:
        cbDrink1.setEnabled(true);
        cbDrink2.setEnabled(true);
        cbDrink3.setEnabled(true);
    }//GEN-LAST:event_cbEnableDActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int total = 0;

        if (cbSnack1.isSelected()){
            total += 35;
        }

        if (cbSnack2.isSelected()){
            total += 50;
        }

        if (cbSnack3.isSelected()){
            total += 45;
        }

        if (cbDrink1.isSelected()){
            total += 25;
        }

        if (cbDrink2.isSelected()){
            total += 20;
        }

        if (cbDrink3.isSelected()){
            total += 15;
        }

        
        int payment = Integer.parseInt(txtPayment.getText());

        int change = payment - total;

        if (payment < total) {
            JOptionPane.showMessageDialog(rootPane, "Insufficient Payment.", "Invalid Payment", JOptionPane.WARNING_MESSAGE);
            return;
        }

        else {
            JOptionPane.showMessageDialog(null, "Total:" + total);
            JOptionPane.showMessageDialog(null, "Change:" + change);
        }
       
        
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Order Again?",
                "Confirmation",
                JOptionPane.YES_NO_OPTION
        );
        
        if (choice == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(
                            null,
                            "You clicked YES!",
                            "Result",
                            JOptionPane.INFORMATION_MESSAGE
                    );      
                      
                    cbSnack1.setSelected(false);
                    cbSnack2.setSelected(false);
                    cbSnack3.setSelected(false);
                    cbDrink1.setSelected(false);
                    cbDrink2.setSelected(false);
                    cbDrink3.setSelected(false);
                    cbSnack1.setEnabled(false);
                    cbSnack2.setEnabled(false);
                    cbSnack3.setEnabled(false);
                    cbDrink1.setEnabled(false);
                    cbDrink2.setEnabled(false);
                    cbDrink3.setEnabled(false);
                    cbEnableS.setSelected(false);
                    cbEnableD.setSelected(false);
                    txtPayment.setText("");
                    lblTotal.setText("Total:");
                    lblChange.setText("Change:");
                    
                } 
        else if (choice == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(
                            null,
                            "You clicked NO!",
                            "Result",
                            JOptionPane.WARNING_MESSAGE
                    );
                    dispose();
        }
        
        lblTotal.setText("Total:" + total);
        lblChange.setText("Change:" + change);
        
   
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotal1ActionPerformed
        
    }//GEN-LAST:event_btnTotal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_dsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_dsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_dsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_dsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_dsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnTotal1;
    private javax.swing.JCheckBox cbDrink1;
    private javax.swing.JCheckBox cbDrink2;
    private javax.swing.JCheckBox cbDrink3;
    private javax.swing.JCheckBox cbEnableD;
    private javax.swing.JCheckBox cbEnableS;
    private javax.swing.JCheckBox cbSnack1;
    private javax.swing.JCheckBox cbSnack2;
    private javax.swing.JCheckBox cbSnack3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtPayment;
    // End of variables declaration//GEN-END:variables
}
